---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-message-dp
  namespace: mod-08-ns
  labels:
    app: web-message
spec:
  selector:
    matchExpressions:
      - { key: web, operator: In, values: [msg] }
      - { key: env, operator: In, values: [dev] }
  replicas: 2
  template:
    metadata:
      name: web-message-pod
      labels:
        web: msg
        env: dev
    spec:
      containers:
      - name: web-message-cntr
        image: us.gcr.io/k8s-artifacts-prod/echoserver:1.10
        ports:
        - containerPort: 8080
      # DefaultTolerationSeconds plugin must be enabled at cluster level
      #   here overrides the cluster config settings
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 15
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 15
