---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
  apiServerAddress: 0.0.0.0 # for ubuntu (vbox/local) use your laptop IP address
  apiServerPort: 63223
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
- role: control-plane
  # to prrove HA when a worker node crashes
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
        extraArgs:
          enable-admission-plugins: DefaultTolerationSeconds
          default-not-ready-toleration-seconds: "10"
          default-unreachable-toleration-seconds: "10"
  # to enable Ingress to avoid use of port forwards
  - | 
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 8080
    hostPort: 8080
    protocol: TCP
- role: worker
  extraMounts:
  - hostPath: ./volume-storage
    containerPath: /var/local-path-provisioner
- role: worker
  extraMounts:
  - hostPath: ./volume-storage
    containerPath: /var/local-path-provisioner
