---

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: 0.0.0.0
  apiServerPort: 63333
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
        extraArgs:
          enable-admission-plugins: DefaultTolerationSeconds
          default-not-ready-toleration-seconds: "10"
          default-unreachable-toleration-seconds: "10"
- role: worker
  extraMounts:
  - hostPath: ./volume-storage
    containerPath: /var/local-path-provisioner
  labels:
    tier: dev
- role: worker
  extraMounts:
  - hostPath: ./volume-storage
    containerPath: /var/local-path-provisioner
  labels:
    tier: prod

