FROM golang:1.17-alpine3.15 as compiler

RUN mkdir -p /go/app

WORKDIR /go/app

COPY go_project/ .

RUN CGO_ENABLED=0 go build -o /go/app/helloworld .

FROM scratch

COPY --from=compiler /go/app/helloworld .

EXPOSE 8888

CMD ["./helloworld"]
