# Nano Server - IIS

FROM microsoft/nanoserver:ltsc2022

ADD https://az880830.vo.msecnd.net/nanoserver-ga-2016/Microsoft-NanoServer-IIS-Package_base_10-0-14393-0.cab /install/Microsoft-NanoServer-IIS-Package_base_10-0-14393-0.cab
ADD https://az880830.vo.msecnd.net/nanoserver-ga-2016/Microsoft-NanoServer-IIS-Package_English_10-0-14393-0.cab /install/Microsoft-NanoServer-IIS-Package_English_10-0-14393-0.cab

RUN Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force & \
    Save-Module -Path "$Env:ProgramFiles\WindowsPowerShell\Modules\" -Name NanoServerPackage & \
    Import-PackageProvider NanoServerPackage & \
    copy C:\Users\Administrator\AppData\Local\NanoServerPackageProvider\sources.txt C:\Users\Administrator\AppData\Local\NanoServerPackageProvider\searchNanoPackageIndex.txt & \
    dism.exe /online /add-package /packagepath:c:\install\Microsoft-NanoServer-IIS-Package_base_10-0-14393-0.cab & \
    dism.exe /online /add-package /packagepath:c:\install\Microsoft-NanoServer-IIS-Package_English_10-0-14393-0.cab & \
    dism.exe /online /add-package /packagepath:c:\install\Microsoft-NanoServer-IIS-Package_base_10-0-14393-0.cab

RUN powershell -command rm -Recurse C:\install -Force