FROM --platform=linux/amd64 node:21.5.0-bullseye AS node-21.5

LABEL description="Node.JS 21.5"

USER root

RUN mkdir -p /opt/web-apps; \
    chown node:node /opt/web-apps

USER node:node

RUN mkdir -p /opt/web-apps/nodejs

WORKDIR /opt/web-apps/nodejs

ADD --chown=node:node node_project/package.json package.json

RUN npm install

COPY --chown=node:node node_project/views views

COPY --chown=node:node node_project/app.js app.js

EXPOSE 8080/tcp

CMD ["node","app.js"]