---
apiVersion: v1
kind: Service
metadata:
  name: echo-app-ep-np-svc
  namespace: mod-08-ns
  labels:
    rsc: echo-app
spec:
  type: NodePort
  selector:
    rsc: echo-app
  ports:
    - name: echo-app-port
      protocol: TCP
      port: 9090
      targetPort: 8080
      nodePort: 30001
