apiVersion: v1
kind: Service
metadata:
  name: nginx-app-eks
  namespace: core-ns
  labels:
    app: nginx-app-eks
spec:
  selector:
    app: nginx-app-eks
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80