apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html-pv-claim
  namespace: default
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 3Gi
