FROM nginx:1.25.3

# Copy the configuration file from the current directory and paste
# it inside the container to the path /etc/nginx/conf.d/default.conf
COPY nginx.default /etc/nginx/conf.d/default.conf
