---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: mod-07-ns
  labels:
    app: nginx-pod
spec:
  containers:
    - name: nginx-cntr
      image: nginx:1.25.2
      ports:
      - containerPort: 80
