apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
  labels:
    author: core
spec:
  containers:
  - name: nginx-cntr
    image: nginx:1.25.3-alpine
    ports:
    - containerPort: 80
