apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharks-hd-dp
  namespace: default
  labels:
    app: sharks-hd-dp
spec:
  selector:
    matchLabels:
      rsc: sharks-hd-app
  replicas: 1
  template:
    metadata:
      name: sharks-hd-pod
      labels:
        rsc: sharks-hd-app
    spec:
      containers:
        - name: sharks-hd-cntr
          image: hectornsanz/sharks:1.0
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.5"
            limits:
              memory: "128Mi"
              cpu: "1.0"
      nodeSelector:
        disktype: hd
