---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-taint-pod
  namespace: default
  labels:
    app: nginx-taint
spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80