---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    app: nginx-app
spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  labels:
    app: nginx-app
spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80        