apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-server-standalone
  namespace: nginx-ns
spec:
  selector:
    matchLabels:
      app: crm-app
  replicas: 1
  template:
    metadata:
      labels:
        app: crm-app
    spec:
      containers:
      - name: nginx-web-server
        image: nginx:1.16-alpine