apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: lab-03-ns
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "200Mi"
        cpu: "700m"