apiVersion: v1
kind: Pod
metadata:
  name: nginx-hr2
spec:
  nodeName: cluster-c-worker2 # schedule pod to specific node
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent

