apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
# preemptionPolicy: Never (pods assign this prioclass then if w/ highest prio cannot preempt other w/ lowest)
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
 