apiVersion: v1
kind: Service
metadata:
  name: echo-web
  namespace: lab-03-ns
  labels:
    app: echo-app
spec:
  type: NodePort
  selector:
    app: echo-app
  ports:
    - name: echo-8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
