apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  labels:
    app: nginx-pvc
spec:
  storageClassName: standard # check in Mirantis Lens the storageclass. Others can be deployed such as aws ebs, cephFS, iSCSI, NFS, local ... 
  volumeMode: Filesystem # mounted as a filesystem in the pod
  accessModes:
    - ReadWriteOnce # mount as rw only by 1 worker node. https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  resources:
    requests:
      storage: 2Gi