apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    rsc: nginx-pod
spec:
  containers:
  - name: nginx-cntr
    image: nginx:1.25.2
    ports:
    - containerPort: 80
      name: "http-server"
    resources:
      requests:
        memory: "500Mi"
        cpu: "0.5"
        ephemeral-storage: "2Gi"
      limits:
        memory: "1000Mi"
        cpu: "1"
        ephemeral-storage: "3Gi"
