apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-pod
  namespace: mod-09-ns
spec:
  containers:
  - image: ubuntu:22.04
    name: empty-dir-cntr
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      medium: Memory
      sizeLimit: 500Mi
